services:
  seaweedfs:
    image: chrislusf/seaweedfs
    container_name: seaweedfs
    ports:
      - '8333:8333'
      - '9333:9333'
      - '19333:19333'
      - '8888:8888'
    volumes:
      - seaweedfs_vow_data:/data
    command: 'server -dir=/data -s3 -s3.port=8333'
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_vow_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_vow
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_vow_data:/data

volumes:
  redis_vow_data:
  pg_vow_data:
  seaweedfs_vow_data:
